version: "3"
services:
  web:
    image: dirkv63/zolse:v1.3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "19031:5000"
    environment:
      - LOGDIR=/logs
      - LOGLEVEL=info
      - NEO4J_USER=neo4j
      - NEO4J_PWD=neo4jneo4j
      - NEO4J_DB=zolse19.db
      - NEO4J_HOST=neodb
      - VERSIONLABEL=OLSE Zomer 2019
    networks:
      - olse-net
    volumes:
      - "olse:/logs"
  neodb:
    image: neo4j:3.5.3
    volumes:
      - "olse:/data"
      - "olse:/logs"
    networks:
      - olse-net
    environment:
      - NEO4J_dbms_active__database=zolse19.db
      - NEO4J_AUTH=neo4j/neo4jneo4j
networks:
  olse-net:
volumes:
  olse: